/* Copyright 2025 Bill Roth */
package com.digiroth.simplebarcodescanner.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single barcode scan event, stored as an entity in the "scan_history" table.
 *
 * @property id The unique identifier for the scan record, automatically generated by the database.
 * @property timestamp The exact time the scan was performed, stored as a UTC Long.
 * @property format The detected barcode format (e.g., QR_CODE, CODE_128), corresponding to [com.google.mlkit.vision.barcode.common.Barcode] constants.
 * @property valueType The type of content encoded in the barcode (e.g., TYPE_URL, TYPE_TEXT), corresponding to [com.google.mlkit.vision.barcode.common.Barcode] constants.
 * @property rawValue The raw, unformatted string data decoded from the barcode.
 */
@Entity(tableName = "scan_history")
data class Scan(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val timestamp: Long,
    val format: Int,
    val valueType: Int,
    val rawValue: String
)
